// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhQEVReQQ-jR1_IDNPedLSmFDH0bqg7k',
    appId: '1:708526037343:web:39ff2841f88a3dec08beea',
    messagingSenderId: '708526037343',
    projectId: 'for-test-df01c',
    authDomain: 'for-test-df01c.firebaseapp.com',
    storageBucket: 'for-test-df01c.appspot.com',
    measurementId: 'G-Y423KT7FCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG7MErQoKfpubNtdgk-HGrVshuoGHoL5A',
    appId: '1:708526037343:android:a26ae38820283c3408beea',
    messagingSenderId: '708526037343',
    projectId: 'for-test-df01c',
    storageBucket: 'for-test-df01c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XJwMbn_e0piMDmKMYJ40JgCXvMmCAVk',
    appId: '1:708526037343:ios:3043bfeb93559c8408beea',
    messagingSenderId: '708526037343',
    projectId: 'for-test-df01c',
    storageBucket: 'for-test-df01c.appspot.com',
    iosClientId: '708526037343-jfdj74st7hthsejgeumes5pr3ncko7k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.forTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2XJwMbn_e0piMDmKMYJ40JgCXvMmCAVk',
    appId: '1:708526037343:ios:3043bfeb93559c8408beea',
    messagingSenderId: '708526037343',
    projectId: 'for-test-df01c',
    storageBucket: 'for-test-df01c.appspot.com',
    iosClientId: '708526037343-jfdj74st7hthsejgeumes5pr3ncko7k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.forTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhQEVReQQ-jR1_IDNPedLSmFDH0bqg7k',
    appId: '1:708526037343:web:a54a14887e81d20908beea',
    messagingSenderId: '708526037343',
    projectId: 'for-test-df01c',
    authDomain: 'for-test-df01c.firebaseapp.com',
    storageBucket: 'for-test-df01c.appspot.com',
    measurementId: 'G-Z2B0QRG2JE',
  );
}
